name: TrueFace
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.6.2=py310h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.4=py310h06a4308_0
  - joblib=1.4.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - numexpr=2.8.4=py310h8879344_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.2=py310h06a4308_0
  - pandas=2.2.1=py310h6a678d5_0
  - pillow=10.3.0=py310h5eee18b_0
  - pip=24.0=py310h06a4308_0
  - platformdirs=3.10.0=py310h06a4308_0
  - pooch=1.7.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.0=h12debd9_5
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.3.1=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.2=py310h06a4308_0
  - scikit-learn=1.4.2=py310h1128e8f_1
  - scipy=1.10.1=py310hd5efca6_0
  - setuptools=69.5.1=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py310h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.3.1=py310_cu121
  - torchtriton=2.3.1=py310
  - torchvision=0.18.1=py310_cu121
  - tqdm=4.66.4=py310h2f386ee_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.2.1=py310h06a4308_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==0.33.0
      - click==8.1.7
      - coloredlogs==15.0.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - diffusers==0.30.1
      - docker-pycreds==0.4.0
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - ftfy==6.2.3
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.24.6
      - humanfriendly==10.0
      - importlib-metadata==8.4.0
      - iopath==0.1.10
      - kiwisolver==1.4.5
      - matplotlib==3.9.2
      - numpy==1.26.4
      - onnx==1.16.1
      - onnxruntime==1.18.0
      - open-clip-torch==2.26.1
      - opencv-python==4.10.0.84
      - portalocker==2.10.1
      - protobuf==5.27.1
      - psutil==6.0.0
      - pyparsing==3.1.2
      - regex==2024.7.24
      - safetensors==0.4.4
      - sentry-sdk==2.10.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - tabulate==0.9.0
      - termcolor==2.4.0
      - timm==1.0.9
      - tokenizers==0.19.1
      - transformers==4.44.2
      - wandb==0.17.5
      - wcwidth==0.2.13
      - yacs==0.1.8
      - zipp==3.20.0
prefix: /home/stefano.dellanna/miniconda3/envs/TrueFace
